version: '3.8'

services:
  okr-backend:
    build:
      context: .
    ports:
      - "2323:8000"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '4'
          memory: 4G
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8000/api/v1/sysinfo" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 2m
    volumes:
      - ../../testdata:/data
