version: "3.8"

services:
  okr-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2324:2324"
    command:
      [
        "java",
        "-jar",
        "/usr/share/okr/graalvm-java-21.jar",
        "-Xms24g",
        "-Xmx24g",
        "-XX:+UseZGC",
        "-XX:+ZGenerational",
      ]
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4G
        reservations:
          cpus: "4"
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:2324/api/v1/sysinfo"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

    volumes:
      - ../../data:/data

  timings:
    build:
      context: ../
      dockerfile: Dockerfile.script

    depends_on:
      okr-backend:
        condition: service_healthy

    command: ["bash", "/tmp/timings_gsc_graalvm_java_jdk.sh"]
    volumes:
      - ../../curl-format.txt:/tmp/curl-format.txt:ro
      - ./timings_gsc_graalvm_java_jdk.sh:/tmp/timings_gsc_graalvm_java_jdk.sh:ro
      - ../../results.txt:/tmp/results.txt
