
sourcefilesFolder: "/home/bumzack/stoff/rust/okr_backend/rust/"


server:
  port: 2323
spring:
  datasource:
    url: jdbc:postgresql://192.168.0.115:5432/shop
#spring.datasource.url                                           =jdbc:postgresql://localhost:54321/dev
    username: shop
    password: shop

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
# Hibernate ddl auto (create, create-drop, validate, update)
        ddl-auto: update
# https://stackoverflow.com/questions/77262813/unsatisfieddependencyexception-error-creating-bean-with-name-healthcontributor
  cloud:
    refresh:
      enabled: false

  threads:
    virtual:
      enabled: true



