version: "3.8"

services:
  okr-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2323:2323"
    command: ["java", "-jar", "/usr/share/okr/java21-reference-impl.jar"]
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4G
        reservations:
          cpus: "4"
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:2323/api/v1/sysinfo"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

    volumes:
      - ../../data:/data

  timings:
    build:
      context: ../
      dockerfile: Dockerfile.script

    depends_on:
      okr-backend:
        condition: service_healthy

    command: ["bash", "/tmp/timings_gsc_ref_impl_java21.sh"]
    volumes:
      - ../../curl-format.txt:/tmp/curl-format.txt:ro
      - ./timings_gsc_ref_impl_java21.sh:/tmp/timings_gsc_ref_impl_java21.sh:ro
      - ../../results.txt:/tmp/results.txt
