version: "3.8"

services:
  okr-backend:
    build:
      context: .
    ports:
      - "2323:8080"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4G
        reservations:
          cpus: "4"
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/api/v1/sysinfo"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

    volumes:
      - ../../data:/data

  timings:
    build:
      context: ../
      dockerfile: Dockerfile.script

    depends_on:
      okr-backend:
        condition: service_healthy

    command: ["bash", "/tmp/timings_bep_ref_impl_java21.sh"]
    volumes:
      - ../../curl-format.txt:/tmp/curl-format.txt:ro
      - ./timings_bep_ref_impl_java21.sh:/tmp/timings_bep_ref_impl_java21.sh:ro
      - ../../results.txt:/tmp/results.txt
