version: "3.8"

services:
  okr-backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Europe/Paris
    build:
      context: .
      dockerfile: src/BackendThingi.Api/Dockerfile
    ports:
      - "2323:8080"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4G
        reservations:
          cpus: "4"
          memory: 4G

    volumes:
      - ../../data:/data
