version: "3.8"

services:
  okr-backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Europe/Paris
    build:
      context: .
      dockerfile: src/BackendThingi.Api/Dockerfile
    ports:
      - "2323:8080"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4G
        reservations:
          cpus: "4"
          memory: 4G

    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/api/v1/sysinfo"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

    volumes:
      - ../../data:/data

  timings:
    build:
      context: ../
      dockerfile: Dockerfile.script

    depends_on:
      okr-backend:
        condition: service_healthy

    command: ["bash", "/tmp/timings_jha_ref_impl_dotnet.sh"]
    volumes:
      - ../../curl-format.txt:/tmp/curl-format.txt:ro
      - ./timings_jha_ref_impl_dotnet.sh:/tmp/timings_jha_ref_impl_dotnet.sh:ro
      - ../../results.txt:/tmp/results.txt
