version: '3.8'

services:
  okr-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12120:12120"
    command: [
      "node", "build/index.js"
    ]
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '4'
          memory: 4G

