server:
  port: 2323


# sourcefilesFolder: "/Users/gsc/stoff/rust/okr_backend/data/"
# sourcefilesFolder: "/Users/gsc/stoff/rust/okr_backend/data/"
# sourcefilesFolder: "/home/bumzack/stoff/rust/okr_backend/data/"


# sourcefilesFolder: "/home/bumzack/stoff/rust/okr_backend/data"


# docker
sourcefilesFolder:  "/data"
