server:
  port: 2323


# sourcefilesFolder: "/Users/gsc/stoff/rust/okr_backend/fulldata/"
# sourcefilesFolder: "/Users/gsc/stoff/rust/okr_backend/testdata/"
# sourcefilesFolder: "/home/bumzack/stoff/rust/okr_backend/fulldata/"

sourcefilesFolder:  "/usr/share/okr/fulldata"
