version: '3.8'

services:
  okr-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9876:9876"
      # debug ports for local development
      - "5005:5005"
    command: [
      "java",
      "-jar", "/usr/share/okr/graalvm-kotlin-21.jar"
    ]
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '4'
          memory: 4G

