version: '3.8'

services:
  okr-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2325:2325"
    command: [
      "java",
      "-jar", "/usr/share/okr/graalvm-kotlin-21.jar"
    ]
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '4'
          memory: 4G

    volumes:
      - ../../data:/data