version: '3.8'

services:
  okr-backend:
    build:
      context: .
      dockerfile: Dockerfile.graal
    ports:
      - "2325:2325"
    command: [
      "/graal-kotlin-app"
    ]
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '4'
          memory: 4G

    volumes:
      - ../../data:/data