[workspace]
resolver = "2"

members = [
    "common",
    "create_dummy_db",
    "warp_backend",
    "frontend",
    "commonbefe",
    "image_resize",
    "wiki",
    "parser_generator",
    "frontend_router"
]
