version: "3.8"

services:
  okr-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "23000:23000"

    command: ["/gsc-rust-axum"]
    environment:
      cores: 4
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4G"
        reservations:
          cpus: "4"
          memory: "4G"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:23000/api/v1/sysinfo"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

    volumes:
      - ../../data:/data

  timings:
    build:
      context: ../
      dockerfile: Dockerfile.script

    depends_on:
      okr-backend:
        condition: service_healthy

    command: ["bash", "/tmp/timings_gsc_rust_axum.sh"]
    volumes:
      - ../../curl-format.txt:/tmp/curl-format.txt:ro
      - ./timings_gsc_rust_axum.sh:/tmp/timings_gsc_rust_axum.sh:ro
      - ../../results.txt:/tmp/results.txt
