version: '3.8'

services:
  okr-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2326:2326"
    command: [
      "/gsc_rust_warp"
    ]
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4G"
        reservations:
          cpus: "4"
          memory: "4G"

    volumes:
      - ../../data:/data
