server:
  port: 2324

spring:
  threads:
    virtual:
      enabled: true


# local
# sourcefilesFolder: "/home/bumzack/stoff/okr_backend/data"
# sourcefilesFolder: "/Users/gsc/stoff/lernen/vi-okr/data"

# docker
sourcefilesFolder:  "/data"
