version: '3.8'

services:
  okr-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2323:2323"
      # debug ports for local development
      - "5005:5005"
    command: [
      "java",
      "-jar", "/usr/share/okr/graalvm-java-21.jar"
    ]
