version: '3.8'

services:
  okr-backend:
    build:
      context: .
      dockerfile: Dockerfile.graal
    ports:
      - "2323:2323"
      # debug ports for local development
      - "5005:5005"
    command: [
      "/graal-java-app"
    ]
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '4'
          memory: 4G

