version: '3.8'

services:
  okr-backend:
    build:
      context: .
      dockerfile: Dockerfile.graal2
    ports:
      - "2323:2323"
      # debug ports for local development
      - "5005:5005"
    command: [
      "graal-ref-impl-app"
    ]
